### PR TITLE
Support windows compilation, add get profiles api, add get snapshot/stream url and save pictures ok

### PR DESCRIPTION
**Pull request by YK-1340**

### CODE REVIEW

**Comment by Quedale** [comment]
Thanks for this pull request for enhancements and new API calls! That's greatly appreciated!

I personally have little interest in windows support, since I don't use it, but I won't reject changes to support it.

I will finish this review and test it as soon as I can. 
From a quick glance it looks good!

I just need to adjust my other repo [OnvifDeviceManager](https://github.com/Quedale/OnvifDeviceManager) currently depending on this library since It doesn't use versioning yet. (so it doesn't break)

Versioning could be easily enabled if it becomes actively used.

**Comment by Quedale** [comment]
While I didn't finish the code review, I did finish the initial test.

Two small things need to be adjusted before I can accept this pull request to avoid breaking anything.

1. httpda.h was added as a dependency and should also be added to `Makefile.am`. Simply add `$(GSOAP_SRC_DIR)/gsoap/plugin/httpda.c` to the line starting with `libonvifsoap_la_SOURCES`
2. Inside `onvif_device.c`, The usage of `dev->profiles` assumes its initialization, which causes a `segment fault` if `OnvifDevice__media_getStreamUri` or `OnvifDevice__media_getSnapshotUri` is invoked before `OnvifDevice_get_profiles`. A simple validation before handling profiles can resolve that:
```
    if(!self->profiles){
        OnvifDevice_get_profiles(self);
    }

    if(profile_index >= self->sizeSrofiles){
        printf("ERROR : profile index out-of-bounds.\n");
        return NULL;
    }

    request.ProfileToken = self->profiles[profile_index].token;
```

I should have additional time to finish the code review over the weekend.

**Comment by YK-1340** [comment]
Regarding the second question, this is my thinking when implementing the code. When calling `OnvifDevice__media_getStreamUri` or `OnvifDevice__media_getSnapshotUri`, you must get `profile_index` from `OnvifDevice::sizeSprofiles`(sorry for this naming problem)  as a necessary parameter. When `OnvifDevice::sizeSprofiles` is 0, You can't continue to call these two methods, but when it is not 0, you will not use the index outside the range of `OnvifDevice::sizeSrofiles` when you use in `profile_index`, but your suggestion can indeed increase the stability of the program,This is a very good suggestion I will add

**Comment by Quedale** [comment]
Thanks for the additions!

I was not necessarily attached to this solution, I just thought a self-initializing variable might be more intuitive, although I get your point. 
The solution could've simply be  checking for the initialization and print an error.
The main goal was to avoid a crash.

I do plan on revisiting this once I jump back on it again to add missing APIs.
I already gained a considerable amount of experience since I wrote this library, so I would probably change a few things.

For the time being, feel free to continue contributing if you need additional API implemented.

I will try to allocate some time tonight to finish the review.

**Comment by Quedale** [comment]
Before I provide this feedback, the reason I want to perform a code review is to stay familiar with my project and also some learning opportunity. I don't claim to have more experience, so it's always open for discussion. 

That being said, here it is.

**Broken**
The last commit did break it once more, because of the "const" qualifier introduced to `OnvifDevice_set_credentials` in `onvif_device.h.`
```
../src/onvif_device.c:384:6: error: conflicting types for 'OnvifDevice_set_credentials'; have 'void(OnvifDevice *, char *, char *)'
../src/onvif_device.h:89:19: note: previous declaration of 'OnvifDevice_set_credentials' with type 'void(OnvifDevice *, const char *, const char *)'
```
The solution is simply to also add the same qualifier to `onvif_device.c`.

**Small improvement - cleaning wrong soap pointer**
Inside method `OnvifDevice_get_profiles` you clean the pointer `self->device_soap->soap` while it should be `self->media_soap->soap`.
That being said, the clean up is invoked when `set_wsse_data` fails, which is before any soap call. 
Does it have any effect?

**Small improvement - soap_malloc**
According to gSoap's `soap_malloc` documentation, the usage of `soap_new_T` is preferable over `soap_malloc`. Althought I don't have an actual reason other than gSoap stating that "it's more powerful".

For instance:
This:
```
req.StreamSetup = (struct tt__StreamSetup*)soap_malloc(self->media_soap->soap,sizeof(struct tt__StreamSetup));
```
Becomes This:
```
req.StreamSetup = soap_new_tt__StreamSetup(self->media_soap->soap,1);
```

**Negligable** (I can address those later)
1. There's also some new warnings
1. Some comments are in Chinese and I would like to keep the project under one language


**Conclusion**
I noticed several great additions, thanks a lot for that!
Let me know if you don't have time. I could take it from there if you don't.

Cheers!

**Comment by Quedale** [comment]
I actually went ahead and merge it as-is and added a few adjustments since I had some spare time tonight.

Thanks you so much for this contribution.

You are officially the first contributor!

**Pull request merged**
